### ISSUE TITLE
Identification of problematic node-edge links and text for the vignette

### ISSUE THREAD

**Issue by pbkeating** [reconhub/epicontacts#101]
Hi,

Would be great if it were possible to highlight erroneous connections between nodes and edges e.g. if the date of onsets completely overlap or if time between cases is greater than the expected serial interval.

Similar to what is been done for the shiny app that is being developed? 

Also, it might be worth adding how to add a title to the plot, when plotting double x-axis.

I did the following:

```r
plot_dec$x$main$text <- "Chaînes de transmission connues, Août-Décembre 2018"
plot_dec$x$main$style <- "font-weight:bold;font-size:20px;text-align:center"
```

Obtained the info from here

https://github.com/datastorm-open/visNetwork/issues/191

**Comment by zkamvar** [comment]
Hi @pbkeating,

> Would be great if it were possible to highlight erroneous connections between nodes and edges e.g. if the date of onsets completely overlap or if time between cases is greater than the expected serial interval.

I can see this as a useful statistic for the epicontacts object itself. Do you think it would be useful to have a pruning mechanism as well that removes these erroneous connections based on a given criteria?


Regarding the next questions, I'll do my best to answer them, but in general, it's best to stick to one topic per issue. 

> Similar to what is been done for the shiny app that is being developed?

The last commit to the shiny app was two years ago by @thibautjombart, which was likely during a hackathon. I'm afraid that there's no current coordinated effort to address that, especially given that epicontacts continues to evolve under @finlaycampbell's might.

> Also, it might be worth adding how to add a title to the plot, when plotting double x-axis.
> 
> I did the following:
> 
> ```r
> plot_dec$x$main$text <- "Chaînes de transmission connues, Août-Décembre 2018"
> plot_dec$x$main$style <- "font-weight:bold;font-size:20px;text-align:center"
> ```
> 
> Obtained the info from here
> 
> [datastorm-open/visNetwork#191](https://github.com/datastorm-open/visNetwork/issues/191)

Good suggestion! Can you open a separate issue for this?

**Comment by pbkeating** [comment]
Hi Zhian,

Thanks a lot for that. 
Thanks for best practice on github. Much appreciated. 
Will ensure that I keep issues separate moving forward.

Regarding the erroneous connections, it's helpful to be able to visualise them in terms of highlighting where errors have been made and where further investigations are necessary.  I think it could also be useful to show a "dirty" vs "clean" transmission chain regarding your point on pruning.

Regarding the shiny app, there is a shiny app developed by Imperial College and has been used during this outbreak and it includes the functionality of identification of erroneous connections and highlights them in yellow. I think it may use the epicontacts package, but not 100% sure.

Thanks!

**Comment by zkamvar** [comment]
> Regarding the shiny app, there is a shiny app developed by Imperial College and has been used during this outbreak and it includes the functionality of identification of erroneous connections and highlights them in yellow. I think it may use the epicontacts package, but not 100% sure.

Do you remember the name of the app? is it https://github.com/reconhub/epicontacts.ui?

**Comment by zkamvar** [comment]
> Regarding the erroneous connections, it's helpful to be able to visualise them in terms of highlighting where errors have been made and where further investigations are necessary. I think it could also be useful to show a "dirty" vs "clean" transmission chain regarding your point on pruning.

@finlaycampbell, is this something that's possible?

**Comment by finlaycampbell** [comment]
Hi Pat,

Thanks for all the useful comments! 

Re highlighting and removing erroneous connections, this is very easily done using epicontacts as is. I've just updated the vignette with an additional section showing how to do this (see 696ed17e5c1ae7ee25138491538fc7339bb32215). I think the question is if we want to include an option within epicontacts that does this behind the scenes - I'm not sure at this point, mainly because there are many different reasons a contact could be considered suspicious for beyond just the SI. I think this is a better use case for an app that calls on epicontacts.

I think Pat means the Shiny app developed by Katy Gaythorpe, which is completely separate and unfortunately involves some duplication. I think she uses ggplot + plotly (which I think is less useful than epicontacts) but she's done more work around highlighting erroneous contacts. We should have a chat with her and see if she wants to use epicontacts for plotting instead.

**Comment by zkamvar** [comment]
Does anyone know where this shiny app lives?

**Comment by pbkeating** [comment]
Hi all,

Thanks for that.
Yes, I was speaking about the Shiny app that Katy Gaythorpe made and
probably best to reach out to her directly.

Finlay, I'll try out the link you suggested and let you know! Thanks both!

P

**Comment by finlaycampbell** [comment]
I think it lives [here](https://github.com/imperialebola2018/chainchecker), though I'm not sure. 

Let me know if you have any more questions, Pat!

**Comment by zkamvar** [comment]
> I think it lives [here](https://github.com/imperialebola2018/chainchecker), though I'm not sure.

I guess that's a private repository, because I get the Octo Wan Catnobi 404 page.

**Comment by finlaycampbell** [comment]
Ah yeh I'd forgotten that's private - maybe you can ask for access? I'm not sure the package itself has anything confidential on it.

**Comment by zkamvar** [comment]
> Ah yeh I'd forgotten that's private - maybe you can ask for access? I'm not sure the package itself has anything confidential on it.

I have no practical use for it, so it was more of a morbid curiosity than anything. I just don't understand the point of closed-source academic software.

**Comment by finlaycampbell** [comment]
Me neither!
