### ISSUE TITLE
New package version & CRAN release?

### ISSUE THREAD

**Issue by joshwlambert** [reconhub/epicontacts#138]
Would it be possible to release the current version of {epicontacts} (mostly likely as a patch release, `v1.1.4`) and submit this new version to CRAN? This would be really helpful to resolve an issue on a package I am developing (see epiverse-trace/simulist#69) which was fixed in {epicontacts} in PR #136. 

I've run R CMD check and there are no errors or warnings, but 1 note. I've also run the [reverse dependency check](https://github.com/r-lib/revdepcheck) which did not produce any errors, however the {doublIn} R package failed to install as it depends on {rjags} which I cannot, at the moment, install on my local computer. However, I suspect this will not be an issue if CRAN ran the checks.

Please let me know if you would be willing to make a release and a CRAN submission, and if I can help with this in any way possible.

**Comment by finlaycampbell** [comment]
Hey Josh, I've just submitted the newest version to CRAN - let's see if they have any complaints. Will let you know!

**Comment by joshwlambert** [comment]
Amazing, thanks for the quick response and submission!
