### ISSUE TITLE
`subset_clusters_by_`... rename `node` to `id` 

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/epicontacts#27]
As our user base will be mostly epidemiologists, it may be better to refer to cases as cases rather than nodes when possible. I think nodes/edges terminology is fine internally, but maybe best avoided on the user side (especially since some functions and the data structure use the 'case/id' terminology. 

@vpnagraj @nistara is it OK with you?

I have made the change at 651a9b2

**Comment by nistara** [comment]
@thibautjombart , yup, it makes total sense to me to change from 'nodes' to 'id'. Thanks!

**Comment by nistara** [comment]
One question, how was it that you changed the name throughout the package? I remember you mentioning a command to do so...

**Comment by vpnagraj** [comment]
@thibautjombart totally fine with me

**Comment by thibautjombart** [comment]
Using emacs: 
find-grep-dired
To find files containing the term, then mark them ('m'), then
dired-do-query-replace
To replace terms
