### ISSUE TITLE
move to reconhub?

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/epicontacts#29]
Hi there, 

are you guys all okay to move the package to github.com/reconhub ? @vpnagraj  @nistara ?

Cheers
Thibaut

**Comment by vpnagraj** [comment]
definitely ... just let me know how you'd like to move forward with that ... and i suppose we'll all need to be added as members to reconhub?

**Comment by nistara** [comment]
Likewise! 

Hope you're all doing great,
Nistara

**Comment by thibautjombart** [comment]
Move made - was just a transfer. Everyone should still be onboard as before. Will send email regarding next stuff soon!

**Comment by vpnagraj** [comment]
@thibautjombart i removed the old remote and added new one now that the repo is on reconhub ... getting a permission denied when i try to push changes ... do i need to be added as a member to reconhub to push changes directly (without forking)?

**Comment by thibautjombart** [comment]
Hi there
sorry about the late reaction. Yes, as it turns out I needed to add you as collaborators. Should be sorted now.
