### ISSUE TITLE
Various fixes for vignette

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/epicontacts#32]
Various things to fix in the vignette:
- [ ] use the same title as package
- [ ] make figures larger (they're way too small now)
- [ ] assume the CRAN release is available
- [ ] fix the first `plot(x)` - nothing is displayed
- [ ] rename _Selection functions by individuals_ to more explicit
- [ ] fix `plot(x_subset_N)`, it looks like a different plot (`plot(x)`)?  
- [ ] fix `plot(net_igraph, ...` : graph is impossible to visualize 
- [ ] fix `renderGraph(g)`: nothing is displayed

**Comment by vpnagraj** [comment]
think i covered most of these ... but see ac963f9 and feel free to reopen if necessary
