### ISSUE TITLE
`clusters_epi_contacts`

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/epicontacts#36]
This is cool, but small changes may be useful. Probably mostly for @nistara (?)
- [x] change arguments to `clusters_epi_contacts(x, output = c("epi_contacts", "factor"))` and then use `output <- match.arg(ouput)` to get the type of output; keep current behaviour by default, but allow for a basic `factor` to be returned, named after IDs. 
- [x] description: say that the function identifies transitive clusters (i.e. connected components) and adds this information to the linelist data; *_question: *_ what happens when individuals from the contacts are not documented in the linelist? Are they added using some kind of `merge`?
- [x] example: rename objects to `x` and `y` or something similar (just shorter)

**Comment by thibautjombart** [comment]
@nistara feel free to close the issue if all done ;)

**Comment by nistara** [comment]
Updated. It now returns either an `epi_contacts` object or a `data.frame` with the ids, cluster members (as factors), and cluster sizes. Individuals from the contacts not documented in the linelist are excluded. They can easily be added if you think it's wise to do so.

**Comment by vpnagraj** [comment]
awesome thanks @nistara :)
