### ISSUE TITLE
Use data from *outbreaks* package

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/epicontacts#37]
remove the current versions from the package and depend on _outbreaks_; it should be a stable package as it only contains data.

**Comment by vpnagraj** [comment]
@thibautjombart I added a data-raw dir and a script to generate the ebola.sim object based on *outbreaks*. It seems like that's the canonical way to do it but let me know if you had something else in mind.  

And l left the mers_kor_14 object in there for now ... will that data be added to *outbreaks* ahead of our first release?

**Comment by thibautjombart** [comment]
Yep, ideally all data should be in outbreaks. @finlaycampbell is now maintaining it, so I'll assign him to the task ;)
