### ISSUE TITLE
rename `cluster_epi_contacts` to `get_clusters`

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/epicontacts#40]
For consistency with other functions (the only one having the class name is the constructor `make_epi_contacts`). 

@nistara I can rename it everywhere quite fast using emacs; lemme know if I should

**Comment by nistara** [comment]
Hey Thibaut, 
This function doesn't get clusters, but assigns cluster IDs to the linelist, making it easier to identify clusters and their respective sizes. I'll think of something more appropriate though. I also will update the documentation for this function!

**Comment by thibautjombart** [comment]
Sorry if I was confused. Where do the cluster IDs come from then?
(sorry can't check code ATM, at a workshop)

**Comment by nistara** [comment]
No worries! It uses igraph to find out the clusters each node belongs to, as well as the sizes of their respective clusters. So in that sense, maybe `get_clusters` should work. Sorry for being roundabout!! I'll make the change (been learning emacs since the hackout :) )

**Comment by nistara** [comment]
Renamed the function and pushed the changes to the `cleanup` branch!
