### ISSUE TITLE
rationalise code in `graph3D`

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/epicontacts#42]
The code currently mixes different cases in the arguments:

``` r
graph3D <- function(epi_contacts,
                    label_column = "id",
                    v_col_by = "NA",
                    v.col = "darkturquoise",
                    g.title = "",
                    g.bg = "white",
                    g.fg = "darkturquoise",
                    v.size = 1,
                    e.size = .5) {
```

We should stick to `snake_case` in all APIs (internal code doesn't matter as much). 
It would be nice to try and use similar arguments in all graphical functions, to the extent that it's possible. For instance:

``` r
function (x, group = "id", annot = c("id"), legend = TRUE, legend_max = 10, 
    col_pal = cases_pal, NA_col = "lightgrey", width = "90%", 
    height = "700px", selector = TRUE, editor = FALSE, ...) 
```

uses a color palette and group definitions to define colors for the vertices, which should be possible here too (?). @nistara @vpnagraj  (and others ;) ) what do you think?

**Comment by nistara** [comment]
@thibautjombart Shall we close this issue now, or do you think we need additional changes?

**Comment by thibautjombart** [comment]
Thanks!
