### ISSUE TITLE
`make_epi_contacts` treat arguments symmetrically

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/epicontacts#43]
There's no real reason why `contacts` should be optional, but not `linelist`.

**Comment by vpnagraj** [comment]
see 2e741d9

**Comment by vpnagraj** [comment]
just had a [PR](https://github.com/reconhub/epicontacts/pull/60) come through from a new contributor to change contacts and line list to each be optional ... right now they are both required to a make an `epicontacts` object, which is the typical use case as i understood it

this would be a pretty big change to the package, and i'm not totally sure what it would mean for plotting, subsetting, etc.

@thibautjombart i sent you a "review request" of the PR i mentioned above

@finlaycampbell @nistara please feel free to chime in here as well

and i'm re-opening this issue as it is the most relevant but i can also create a new issue if that's easier to track

**Comment by vpnagraj** [comment]
err nevermind ... the contributor just closed the [PR](https://github.com/reconhub/epicontacts/pull/60) 

but feel free to reopen this issue again if you all think this a use case we should consider

**Comment by thibautjombart** [comment]
Hi there, 
Dirk and I are working on a separate RECON project using epicontacts and we started hitting corner cases. Nothing that can't be solved easily, but worth discussing. I previously thought that `contacts` should be mandatory, and that `linelist` was optional. However, if the package is going to serve as backend to other systems, Dirk pointed out data entry will typically start from empty objects. So it looks like we should allow empty slots and have a test e.g. `if (!is.null(x$contacts)) { ... }`
What do you think?

**Comment by thibautjombart** [comment]
BTW I'm on slack too to discuss if faster. ;)
