### ISSUE TITLE
Add 'details' section to doc of `make_epi_contacts`

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/epicontacts#44]
So far it is referred to, but does not exist.

**Comment by vpnagraj** [comment]
dacc15a ... added details section and made some minor edits / formatting changes to make_epi_contacts doc 

@thibautjombart i'll leave this issue open until you review since you had self-assigned ... if all looks good feel free to close

**Comment by thibautjombart** [comment]
Yep, thanks for flagging this! 
Just reformatted the doc a bit and closing via 5690e79647a1d8d9fd4ef47a3541527a4afb8ae1
