### ISSUE TITLE
Tidy up subset function

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/epicontacts#52]
It probably does the right job as it stands, but it is really hard to figure out what's going on there:
https://github.com/reconhub/epicontacts/blob/master/R/subset.epi_contacts.R

A few tips that I found useful:
- make intermediate variables with explicit names
- short command lines (<80 characters) where possible
- comments explaining what is being done whenever there's something non-trivial, so that someone could recode the function from your comments

The idea is that anyone should be able to look at this code and patch it if needed

**Comment by finlaycampbell** [comment]
Fixed in 845fd39

**Comment by thibautjombart** [comment]
Tidied up at d91617d8a8ad1f9b0f4ae1d4d80323555db4bb72

Misc things:
- prefer `vapply` to `sapply`
