### ISSUE TITLE
epicontacts versus epi_contacts

### ISSUE THREAD

**Issue by vpnagraj** [reconhub/epicontacts#59]
i was just about to get started on the [vignette for data structure](https://github.com/reconhub/epicontacts/issues/54) and it occurred to me that while we call the package **epicontacts**, the s3 class is `epi_contacts`. for the sake of consistency we might want to rename the data structure to `epicontacts`. 

not a huge deal to me ... do you all have any strong feelings on this? let me know if you'd like to me to make the change, if one of you would prefer to jump in and do it or if we should just leave everything as-is.

@thibautjombart @nistara @finlaycampbell

**Comment by thibautjombart** [comment]
I think you're right. Go for it ;)

On 13 Dec 2016 22:38, "VP Nagraj" <notifications@github.com> wrote:
>
> i was just about to get started on the vignette for data structure and it
occurred to me that while we call the package epicontacts, the s3 class is
epi_contacts. for the sake of consistency we might want to rename the data
structure to epicontacts.
>
> not a huge deal to me ... do you all have any strong feelings on this?
let me know if you'd like to me to make the change, if one of you would
prefer to jump in and do it or if we should just leave everything as-is.

**Comment by thibautjombart** [comment]
I'm on it. Will push soon.

**Comment by thibautjombart** [comment]
done as of eccb70626cfba992d523fe0270cbdc7d3f86665f

**Comment by vpnagraj** [comment]
@thibautjombart wow thanks for jumping on that so quickly looks great 👍
