### ISSUE TITLE
Suppose linelist has a column named "group"

### ISSUE THREAD

**Issue by nistara** [reconhub/epicontacts#71]
Not sure if this is an issue, but say the linelist already has a column named `group`. In that case, the following code would overwrite the original column, and the annotations would contain the new group values instead of the original ones.
```
  ## join back to linelist to retrieve attributes for grouping

  nodes <- suppressMessages(
    suppressWarnings(dplyr::left_join(nodes, x$linelist)))
  nodes$group <- as.character(nodes[, group])
  nodes$group[is.na(nodes$group)] <- "NA"
  nodes$group <- factor(nodes$group)


  ## get annotations

  temp <- nodes[, annot, drop = FALSE]
  temp <- sapply(names(temp), function(e) paste(e, temp[, e], sep = ": "))
  nodes$title <- paste("<p>",
                       apply(temp, 1, paste0, collapse = "<br>"), "</p>")
```
To avoid the overwriting in  `graph3D`(), I got the annotations first and then did the grouping process. Do you think we should do the same for `vis_epicontacts()`?
@thibautjombart ?

**Comment by thibautjombart** [comment]
Thanks for flagging this. 
I think the behaviour of `get_clusters` should be defined first, and its call in other function is a separate issue. 
How about adding an argument `col_name = "group"` which will be used to name the added column containing groups. And throw an error if this name is already in the linelist? Or even maybe better, add an argument `override = FALSE` to decide if this checking/error should be done (`FALSE`, default), or if previous column should be erased without checks (``TRUE`)

**Comment by nistara** [comment]
Thanks for the suggestions! So this would need to be done for 'as.igraph', 'get_clusters', 'graph3D', and 'vis_epicontacts'. Basically any function of ours that's creating new columns within it for whatever reason.

**Comment by thibautjombart** [comment]
Haha, great that you picked that up. It would be good to avoid this as much as possible so that functions remain as simple as they can, at least on the user side. I guess we can distinguish two cases:
1. we add columns to the linelist for internal purposes
2. we add columns to the linelist as part of the intended output

I guess the first is to be avoided to the extent possible. I am looking at the cases you mentioned:

In `as.igraph`:
```{r}
  ## Checking if a "name" column exists

  if ("name" %in% colnames(verts)) {
    verts$epicontacts_name <- verts$name
    verts$name <- NULL
  }

  ## Creating igraph object

  net <- igraph::graph_from_data_frame(x$contacts, vertices = verts,
                                       directed = x$directed)

  igraph::vertex_attr(net)$id <- igraph::vertex_attr(net)$name

```
What happens if there is a column called 'name' in `verts` when calling `graph_from_data_frame`?

**Comment by nistara** [comment]
For `graph_from_data_frame`, I first checked if a column called `name` existed. If yes, I saved it to a new column, `epicontacts_name`, and mentioned that in the documentation:
```
Note: any
#'   column called "name" in the original linelist will be stored as a new
#'   vertex attribute in the \code{igraph} object named 'epicontacts_name'.
#'   This is due to the inherent behaviour of igraph creating its own 'name'
#'   vertex attribute.
```
That's because `igraph`  takes the first column while creating an `igraph` object, and assigns it to the `name` column (from [here](http://igraph.org/r/doc/graph_from_data_frame.html):

```
If vertices is not NULL, then it must be a data frame giving vertex metadata. The first column of vertices is assumed to contain symbolic vertex names, this will be added to the graphs as the ‘name’ vertex attribute. Other columns will be added as additional vertex attributes. If vertices is not NULL then the symbolic edge list given in d is checked to contain only vertex names listed in vertices.
```

I think I should implement your suggestion of adding an argument `override = FALSE` to check if there are existing columns with names that could be overwritten, and throw an error if yes (and `override = FALSE`), or not if `override = TRUE`.

Talking about documentation, I realize I used `behaviour` instead of `behavior`, in the documentation out of sheer habit. Are we following American English, or it doesn't matter?!

**Comment by nistara** [comment]
In contd...: so the `graph_from_data_frame` takes the first column, `id` as its `name` column. If it exists already, it was being saved to `epicontacts_name`. In either case, the original `id` column was added back as a vertex attribute (from the now `name` column). 
Gosh, this sounds convoluted!

**Comment by thibautjombart** [comment]
OK makes sense, thanks for the explanation. I think it's fine as it is, this is just plotting after all, not something that alters the object returned. 

I'm finishing a new version of `vis_epicontacts`. Looking at the code I realised some crappy bits ':-)

**Comment by nistara** [comment]
Alrighty then. I'll edit the code for the `get_clusters` tonight, and look for your changes to `vis_epicontacts`, since I modeled `graph3D` along it. 
Thanks for your help!

**Comment by thibautjombart** [comment]
closed via: ccce2ae74f6d8a9e73f8e1a03a2123fe7cc12ddc

notable changes to handling `group` and `annot` include cases where there is a `group` in the linelist, and info provided as integer or logical, e.g. 
https://github.com/reconhub/epicontacts/blob/master/R/vis_epicontacts.R#L89-L118

**Comment by vpnagraj** [comment]
@nistara and @thibautjombart let me know when / if we can close this issue ... then i can move onto #67 :)

**Comment by nistara** [comment]
I'll tackle it tonight :)

**Comment by nistara** [comment]
See [704d86b](https://github.com/reconhub/epicontacts/commit/704d86b9dd45d0fa9532b0b33d161d591cf48b52)

It now checks if cluster member/size columns already exist in the linelist. If yes, and `override = FALSE`, it will throw an error and ask the user to change the respective column name(s). If yes, and `override = TRUE`, it'll drop the duplicate column(s) before adding cluster columns again.
