### ISSUE TITLE
Update `epicontacts` site

### ISSUE THREAD

**Issue by nistara** [reconhub/epicontacts#73]
It lists `get_clusters()` by its previous name (`clusters_epicontacts`).

**Comment by thibautjombart** [comment]
Should be fixed via f218df7eb5fc48386f3ff5c8210044bb79ab8e64

**Comment by nistara** [comment]
Thanks! We have another small type now, which I've fixed in the readme's:
[c24cd1c](http://www.vetmed.ucdavis.edu/ohi/predict/index.cfm)
