### ISSUE TITLE
NOTE ON 'ebola' BRANCH

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/epicontacts#78]
@nistara @vpnagraj @finlaycampbell Just to let you know, I will be making an 'ebola' branch to implement changes to the package to accommodate needs for the Ebola outbreak in DRC. Most of these will be along the lines of customisation of the plot as in [dibbler](https://github.com/reconhub/dibbler) (see `?plot.dibbler`):

- using icons to display linelist info
- using colors or symbols for edges to display contacts info

**Comment by nistara** [comment]
Sounds good @thibautjombart. Glad to see this being useful for the current Ebola outbreak.

**Comment by thibautjombart** [comment]
It is! I have just seen an internal report which was using it. I've merged back onto master what was stable. See the new parameter `node_shape` and `shapes` in `vis_epicontacts`. Using fontawesome for icons is actually useful to convey more info

**Comment by nistara** [comment]
Great, thanks for letting me know of this and about fontawesome!

**Comment by vpnagraj** [comment]
@thibautjombart @nistara the font awesome icons is a great feature ... thanks for adding!

i was running into an issue where the icons weren't rendering, so i added a call to `visNetwork::useFontAwesome()` in `vis_epicontacts()` (8ee1255)

closing this for now, feel free to open back up or start a new issue if you notice any other bugs

**Comment by thibautjombart** [comment]
Great, thanks!
