### ISSUE TITLE
Use consistent thining in plot.epicontacts / vis_epicontacts

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/epicontacts#81]
Currently, `plot.epicontacts` by default thins the data and uses `vis_epicontacts` to plot the output.

However, `vis_epicontacts` has no thinning by default, resulting in different outputs. This has confused some users during the Epidemics6 workshop, maybe we want to think about it.

**Comment by vpnagraj** [comment]
as of 7766820  `plot.epicontacts` and `vis_epicontacts` both handle thinning the same way

thanks for raising this issue @thibautjombart

- [ ]
