### ISSUE TITLE
Add time to epicontacts graph

### ISSUE THREAD

**Issue by finlaycampbell** [reconhub/epicontacts#82]
Add x-axis to represent time

**Comment by vpnagraj** [comment]
twitter thread related to this:

https://twitter.com/jonny_polonsky/status/1019595818054057990

**Comment by finlaycampbell** [comment]
I made a very quick attempt to specify an x axis with a given column ID from the contacts dataframe - see commit f70e99a17f0f62fdd743c4ee9c104216cdee610d on branch xaxis. It uses the visHierarchical option within visNetwork and so was easy to implement, not sure how good it really looks though

**Comment by vpnagraj** [comment]
thanks @finlaycampbell for working on this ... added to to `master` via eb5bf0
