### ISSUE TITLE
vis_epicontacts does not display nodes if x_axis is specified and thin = FALSE

### ISSUE THREAD

**Issue by zkamvar** [reconhub/epicontacts#86]

**Comment by zkamvar** [comment]
I found the issue: visHierarchicalLayout does not play nicely if there are missing data in the x-axis. The solution is either to remove the nodes with missing x-axis information OR to find a way to give them an arbitrary date and clearly label them as not having an associated date on the x axis

**Comment by vpnagraj** [comment]
thanks @zkamvar just merged #87 with the fix for this
