### ISSUE TITLE
visNetwork error when trying to make trees based on date of onset

### ISSUE THREAD

**Issue by pbkeating** [reconhub/epicontacts#99]
Hi,

I'm using epicontacts_1.2.0 to be able to make transmission chains with date of onset as axis The regular plot without the time component works fine `plot(x,"hcw", col_pal = spectral)`, but each time I try to make the tree with date of onset, I get the following message:

**Error in visNetwork::visNetwork(nodes, edges, width = width, height = height) : 
  nodes must have unique ids**

Would you have any suggestions on how I can overcome this?
Below the code used to make the tree:

 po <- plot(x,

           method = 'ttree',

           x_axis = 'date_onset',

           position_dodge = TRUE,

           node_color = 'hcw',

           col_pal = colorRampPalette(c("#427A82", "#AA6F39")),

           node_size = 'R_i',

           date_labels = "%d %b",

           hide_labels = FALSE,

           double_axis = TRUE,

           thin = FALSE)

**Comment by finlaycampbell** [comment]
Hi Patrick, I just pushed a potential fix to the `ttree` branch - let me know if it solves the problem!

**Comment by pbkeating** [comment]
Hi Finlay,

Thanks a lot.
I'll install it and let you know.
P

**Comment by pbkeating** [comment]
I removed the previous version of epicontacts and used the below code to install from the branch

`githubinstall::gh_install_packages("epicontacts", ref = "ttree")`

But  get this error message. Any thoughts?
![20190507_104012 1](https://user-images.githubusercontent.com/20238915/57286107-e3d01580-70b4-11e9-9247-722afe9f122d.jpg)

**Comment by finlaycampbell** [comment]
Hm not entirely sure - I would try first restarting your R session and attempting a re-install. If that doesn't work, I'd try deleting the `epicontacts` folder in `win-library/3.5/` and then re-install.

**Comment by zkamvar** [comment]
Hi @pbkeating,

This is most likely due to a contaminated R environment. Finlay is correct in suggesting you restart your R session. 

I would also recommend the following:

1. Use `remotes::install_github("reconhub/epicontacts@ttree")` instead of `githubinstall`. The remotes package doesn't import anything and is generally safer for installing github packages.
2. Make sure that you have your setup like this: https://github.com/R4EPI/sitrep/wiki/1)-Getting-started

**Comment by pbkeating** [comment]
Thanks to you both.
I made the suggested changes from the sitrep wiki. Thanks for those!
I uninstalled the previous version of epicontacts, which is installed as standard as part of the infrastructure (version 1.1.0)

I used the above remotes package to install the updated version of the package, but I get the following message:

![20190507_123433 1](https://user-images.githubusercontent.com/20238915/57293425-02d6a380-70c5-11e9-8752-cc0f2ce90252.jpg)

Any ideas?

**Comment by zkamvar** [comment]
Check if you have an extra .RData hanging around in your working directory
and remove it. Make sure you don't get any messages about a previous
workspace being loaded.

**Comment by pbkeating** [comment]
Hi! Thanks a lot. Just removed the .RData and it now works.
The output is not exactly what I expected, as I thought I would only see the known transmission chains i.e. those that I identified in my contacts sheet, but I spoke to Franck and he explained his approach. 

Is there an option to exclude the IDs without known links within the function?
Thanks!

**Comment by finlaycampbell** [comment]
If you mean removing nodes that don't have any contacts, set `thin = TRUE` and it should remove them. If that's not what you mean you'll have to explain further!

**Comment by pbkeating** [comment]
Hi Finlay, yep, that's exactly what I meant, removing nodes that don't have any contacts!  Still learning the terminology. It's a lot better! This is great! Thanks!
